/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugascrud;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Frame_Main extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Main
     */
    public Frame_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        Nis = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Kelas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        No = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        P = new javax.swing.JRadioButton();
        L = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Nama1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(229, 229, 229));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 198));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(530, 10, 80, 40);

        jButton5.setBackground(new java.awt.Color(213, 230, 255));
        jButton5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(410, 10, 80, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(290, 10, 80, 40);

        jButton3.setBackground(new java.awt.Color(255, 234, 204));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(170, 10, 80, 40);

        jButton2.setBackground(new java.awt.Color(200, 255, 200));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(50, 10, 80, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(290, 90, 660, 60);

        tblData.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kel.", "Kelas", "No. HP", "Alamat Tinggal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 170, 640, 380);

        jPanel3.setBackground(new java.awt.Color(229, 229, 229));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(290, 160, 660, 400);

        Nis.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        getContentPane().add(Nis);
        Nis.setBounds(40, 160, 220, 30);

        Nama.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        getContentPane().add(Nama);
        Nama.setBounds(40, 220, 220, 30);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("NIS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 130, 80, 30);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Nama");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 190, 100, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Jenis Kelamin");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 250, 140, 30);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Kelas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 310, 100, 30);

        Kelas.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        getContentPane().add(Kelas);
        Kelas.setBounds(40, 340, 220, 30);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("No. HP");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 370, 100, 30);

        No.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        getContentPane().add(No);
        No.setBounds(40, 400, 220, 30);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Alamat Tinggal");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 430, 110, 30);

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("DATA SISWA PEMILIK");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(50, 0, 210, 30);

        Alamat.setColumns(20);
        Alamat.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        Alamat.setRows(5);
        jScrollPane2.setViewportView(Alamat);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 370, 220, 80);

        P.setBackground(new java.awt.Color(229, 229, 229));
        buttonGroup1.add(P);
        P.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        P.setText("P");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        jPanel2.add(P);
        P.setBounds(110, 190, 50, 30);

        L.setBackground(new java.awt.Color(229, 229, 229));
        buttonGroup1.add(L);
        L.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        L.setText("L");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });
        jPanel2.add(L);
        L.setBounds(20, 190, 50, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 90, 260, 470);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(229, 229, 229));
        jLabel2.setText("SARPRA SMK TELKOM MALANG");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 50, 290, 20);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BARANG TERTINGGAL");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 10, 410, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 990, 80);

        jPanel5.setBackground(new java.awt.Color(153, 204, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 80, 970, 490);

        Nama1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        getContentPane().add(Nama1);
        Nama1.setBounds(40, 220, 220, 30);

        setSize(new java.awt.Dimension(986, 604));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("".equals(Nis.getText()) || "".equals(Alamat.getText()) || "".equals(Kelas.getText()) || "".equals(Nama.getText()) || "".equals(No.getText()))
        {
            JOptionPane.showMessageDialog(this, "ANDA HARUS MELENGKAPI DATA", "Error", JOptionPane.WARNING_MESSAGE);
        }else
        {
            String JK = "";
            if (L.isSelected())
            {
                JK = "L";
            }else
            {
                JK = "P";
            }
            String SQL = "UPDATE tb_siswa SET "
                    + "NamaSiswa='"+Nama.getText()+"', JenisKelamin='"+JK+"', "
                    + "Kelas='"+Kelas.getText()+"', No='"+No.getText()+"', "
                    + "Alamat='"+Alamat.getText()+"' "
                    + "WHERE NIS='"+Nis.getText()+"'";           
            int status = KoneksiDB.execute(SQL);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "DATA BERHASIL DIUPDATE", "GAGAL!", JOptionPane.WARNING_MESSAGE);
                try {
                    selectData();
                } catch (SQLException ex) {
                    Logger.getLogger(Frame_Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else
            {
                JOptionPane.showMessageDialog(this, "DATA GAGAL DIUPDATE", "GAGAL!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            selectData();
        } catch (SQLException ex) {
            Logger.getLogger(Frame_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Nama.setText("");
        Nis.setText("");
        Kelas.setText("");
        buttonGroup1.clearSelection();
        No.setText("");
        Alamat.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int baris = tblData.getSelectedRow();
        if (baris != -1)
        {
            String NIS = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "DATA BERHASIL DIHAPUS", "SUKSES!", JOptionPane.INFORMATION_MESSAGE);
            }else
            {
                JOptionPane.showMessageDialog(this, "DATA GAGAL DIHAPUS", "GAGAL!", JOptionPane.WARNING_MESSAGE);
            }
        }else
        {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin Anda hapus terlebih dahulu!", "ERROR!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if("".equals(Nis.getText()) || "".equals(Alamat.getText()) || "".equals(Kelas.getText()) || "".equals(Nama.getText()) || "".equals(No.getText()))
        {
            JOptionPane.showMessageDialog(this, "ANDA HARUS MELENGKAPI DATA", "Error", JOptionPane.WARNING_MESSAGE);
        }else
        {
            String JK = "";
            if (L.isSelected())
            {
                JK = "L";
            }else
            {
                JK = "P";
            }
            String SQL = "INSERT INTO tb_siswa (NIS,NamaSiswa,JenisKelamin,Kelas,No,Alamat) "
                    + "VALUES('"+Nis.getText()+"','"+Nama.getText()+"','"+JK+"',"
                    + "'"+Kelas.getText()+"','"+No.getText()+"','"+Alamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1)
            {
                JOptionPane.showMessageDialog(this, "DATA BERHASIL DITAMBAHKAN", "GAGAL!", JOptionPane.WARNING_MESSAGE);
                try {
                    selectData();
                } catch (SQLException ex) {
                    Logger.getLogger(Frame_Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else
            {
                JOptionPane.showMessageDialog(this, "DATA GAGAL DITAMBAHKAN", "GAGAL!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        int baris = tblData.getSelectedRow();
        if(baris != -1)
        {
            Nis.setText(tblData.getValueAt(baris, 0).toString());
            Nama.setText(tblData.getValueAt(baris, 1).toString());
            if("Laki-laki".equals(tblData.getValueAt(baris, 2).toString()))
            {
                L.setSelected(true);
            }else
            {
                P.setSelected(true);
            }
            Kelas.setText(tblData.getValueAt(baris, 3).toString());
            No.setText(tblData.getValueAt(baris, 4).toString());
            Alamat.setText(tblData.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JTextField Kelas;
    private javax.swing.JRadioButton L;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nama1;
    private javax.swing.JTextField Nis;
    private javax.swing.JTextField No;
    private javax.swing.JRadioButton P;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    private void selectData() throws SQLException {
        String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","No","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try
        {
            while(rs.next())
            {
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String JenisKelamin = "";
                if("L".equals(rs.getString(3)))
                {
                    JenisKelamin = "Laki-laki";
                }else
                {
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(4);
                String No = rs.getString(5);
                String Alamat = rs.getString(6);
                String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,No,Alamat};
                dtm.addRow(data);
            }
        }catch (SQLException ex)
        {
            Logger.getLogger(Frame_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
    }
}
